# Generated by Django 4.1.7 on 2023-04-29 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Book',
            fields=[
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('password', models.CharField(max_length=64)),
                ('count_public_book', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('pred', models.TextField(max_length=1000)),
                ('text', models.TextField(max_length=100000000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.users_book')),
            ],
        ),
    ]
