# Generated by Django 4.1.7 on 2023-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
