# Generated by Django 4.1.7 on 2023-04-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data',
            new_name='date',
        ),
    ]
