# Generated by Django 4.1.7 on 2023-04-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_book_date_alter_book_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_book',
            name='desc',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
