# Generated by Django 4.1.7 on 2023-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_users_book_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='see',
            field=models.IntegerField(null=True),
        ),
    ]
