# Generated by Django 4.1.7 on 2023-04-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_book_see'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=60)),
                ('author', models.CharField(max_length=120)),
                ('comment', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
